"""Customer-facing PDF export."""

from __future__ import annotations

from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from carro.config import DATA_DIR, load_config
from carro.core.models import RepairOrder


def export_pdf(order: RepairOrder, dest: Path | None = None) -> Path:
    cfg = load_config()
    shop = cfg.get("shop_name") or "Shop"
    out_dir = DATA_DIR / "pdf"
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = dest or (out_dir / f"{order.id}.pdf")

    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "ROTitle",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=6,
    )
    h2 = ParagraphStyle(
        "ROH2",
        parent=styles["Heading2"],
        fontSize=12,
        spaceBefore=12,
        spaceAfter=6,
    )
    body = styles["Normal"]

    doc = SimpleDocTemplate(
        str(dest),
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
    )
    story = []
    story.append(Paragraph(shop, title))
    story.append(Paragraph(f"Repair Order <b>{order.id}</b>", body))
    story.append(Paragraph(f"Status: {order.status} · Updated: {order.updated}", body))
    story.append(Spacer(1, 0.2 * inch))

    cust = [
        ["Customer", order.customer_label()],
        ["Phone", order.phone or "—"],
        ["Vehicle", order.vehicle_label()],
        ["VIN", order.vin or "—"],
        ["Mileage", order.mileage or "—"],
        ["Plate", order.plate or "—"],
    ]
    t = Table(cust, colWidths=[1.3 * inch, 5.2 * inch])
    t.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(t)

    story.append(Paragraph("Customer complaint / request", h2))
    story.append(Paragraph((order.complaint or "—").replace("\n", "<br/>"), body))

    story.append(Paragraph("Technician notes", h2))
    story.append(Paragraph((order.tech_notes or "—").replace("\n", "<br/>"), body))

    if order.obd_snapshot.strip():
        story.append(Paragraph("OBD snapshot", h2))
        story.append(
            Paragraph(
                f"<font face='Courier' size='8'>{order.obd_snapshot.replace(chr(10), '<br/>')}</font>",
                body,
            )
        )

    photo_paths = []
    for meta in order.photos:
        rel = meta.get("relpath") or meta.get("filename")
        if not rel:
            continue
        p = DATA_DIR / "photos" / order.id / Path(rel).name
        if p.is_file():
            photo_paths.append((meta.get("tag", "other"), p))

    if photo_paths:
        story.append(Paragraph("Photos", h2))
        row = []
        for tag, path in photo_paths[:8]:
            try:
                img = Image(str(path), width=2.2 * inch, height=1.6 * inch, kind="proportional")
            except Exception:
                continue
            cell = [img, Paragraph(f"<i>{tag}</i>", body)]
            row.append(cell)
            if len(row) == 2:
                story.append(Table([row], colWidths=[3.2 * inch, 3.2 * inch]))
                row = []
        if row:
            while len(row) < 2:
                row.append("")
            story.append(Table([row], colWidths=[3.2 * inch, 3.2 * inch]))

    story.append(Spacer(1, 0.3 * inch))
    story.append(
        Paragraph(
            f"<font size='8' color='#666666'>Generated by Car-RO · {order.id}</font>",
            body,
        )
    )
    doc.build(story)
    return dest
